version: "3"

services:
  unbound:
    image: "mvance/unbound:latest"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    volumes:
      - /volume1/docker/filter/unbound:/opt/unbound/etc/unbound/
    ports:
      - 533:53/udp
      - 533:53/tcp
    mac_address: d0:ca:ab:cd:ef:02
    networks:
      home:
        ipv4_address: 192.168.0.201
    restart: always

  wireguard:
    depends_on: [unbound, pihole]
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin # Change to your timezone
      - SERVERPORT=51820
      #- SERVERURL=my.ddns.net #optional - For use with DDNS (Uncomment to use)
      - PEERS=1 # How many peers to generate for you (clients)
      - PEERDNS=192.168.0.200 # Set it to point to pihole
      - INTERNAL_SUBNET=10.6.0.0
    volumes:
      - /volume1/docker/filter/wireguard:/config
      - /volume1/docker/filter/wireguard/lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    dns:
      - 192.168.0.200 # Points to pihole
      - 192.168.0.201 # Points to unbound
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

    restart: unless-stopped
    mac_address: d0:ca:ab:cd:ef:03
    networks:
      home:
        ipv4_address: 192.168.0.202

  pihole:
    depends_on: [unbound]
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: pihole
    dns:
      - 127.0.0.1
      - 192.168.0.201 # Points to unbound
    environment:
      TZ: Europe/Berlin
      WEBPASSWORD: "" # Blank password - Can be whatever you want.
      ServerIP: 192.168.0.200 # Internal IP of pihole
      DNS1: 192.168.0.201 # Unbound IP
      DNS2: 192.168.0.201 # If we don't specify two, it will auto pick google.
    # Volumes store your data between container upgrades
    volumes:
      - /volume1/docker/filter/pihole/etc-pihole/:/etc/pihole/
      - /volume1/docker/filter/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    mac_address: d0:ca:ab:cd:ef:01
    networks:
      home:
        ipv4_address: 192.168.0.200
    restart: always
networks:
  home:
    driver: macvlan
    driver_opts:
      parent: eth1
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
          ip_range: 192.168.0.200/30 # 192.168.1.5 and 192.168.1.6
